views.py
from flask import Blueprint, render_template, flash,request,redirect, url_for
from flask_login import login_required, current_user
from sqlalchemy.exc import IntegrityError
from flask import jsonify, get_flashed_messages
from .check_functions import *
from sqlalchemy import exists
import json


views = Blueprint('views', __name__) 
from . import db


@views.route('/', methods=['GET','POST'])
# @login_required #can only access the home page if logged in
def home():

    from .models import Zone 
    countries_with_lez =Zone.get_countries()
    cities_by_country=Zone.get_countries_and_cities()


    return render_template("home.html", user = current_user, countries_with_lez=countries_with_lez, cities_by_country=cities_by_country)


@views.route('/cities')
def get_cities():
  # Assuming you have a function to fetch cities with country information
  cities = Zone.query.with_entities(Zone.city, Zone.country).distinct().all()  # Include country field
  city_data = []
  for city in cities:
    city_data.append({'city': city[0], 'country': city[1]})  # Create dictionary with city and country
  return jsonify({'cities': city_data})


@views.route('/pollution', methods=['GET','POST'])
def polution():

    return render_template("pollution.html", user = current_user)


@views.route('/unauthorized')
def unauthorized():
    return "You are not authorized to access this page."


@views.route('/admin_dashboard')
@login_required
def admin_dashboard():
    from .models import ZoneTemporaryData
    if current_user.is_authenticated and current_user.is_admin:
        # Perform a join operation to fetch data from both tables
        combined_data = db.session.query(Zone, ZoneTemporaryData).\
            filter(Zone.id == ZoneTemporaryData.zone_id).all()

        # Pass the combined data to the template
        return render_template("admin_dashboard.html", user=current_user, combined_data=combined_data)
    else:
        return "You are not authorized to access this page."
    
    
@views.route('/update', methods=['POST'])
@login_required
def update_zone_table():
    data = request.get_json()  # Get the JSON data from the request body
    from .models import Zone, ZoneTemporaryData
    # Iterate over the data and update each entry
    try:
        for entry in data:
            zone_id = entry.get('id')
            if not zone_id:
                return jsonify({'message': 'ID is required for all entries.'}), 400

            zone = Zone.query.get(zone_id)
            if zone:
                # Update existing Zone object if it exists
                zone.country = entry.get('country')
                zone.city = entry.get('city')
                zone.registration_class = entry.get('registration_class')
                zone.minimum_diesel = entry.get('minimum_diesel')
                zone.minimum_petrol = entry.get('minimum_petrol')
                zone.fines = entry.get('fines')
                zone.registration_type = entry.get('registration_type')
                zone.registration_validity = entry.get('registration_validity')
                zone.required_registration = entry.get('required_registration')
                zone.exception_country = entry.get('exception_country')
                zone.official_page = entry.get('official_page')
                zone.description = entry.get('description')
                zone.city_alias = entry.get('city_alias')

            else:
                # Create a new Zone object if it doesn't exist
                zone = Zone(
                    id=zone_id,  # Assign the provided ID
                    country=entry.get('country'),
                    city=entry.get('city'),
                    registration_class=entry.get('registration_class'),
                    minimum_diesel=entry.get('minimum_diesel'),
                    minimum_petrol=entry.get('minimum_petrol'),
                    fines=entry.get('fines'),
                    registration_type=entry.get('registration_type'),
                    registration_validity=entry.get('registration_validity'),
                    required_registration=entry.get('required_registration'),
                    exception_country=entry.get('exception_country'),
                    official_page=entry.get('official_page'),
                    description=entry.get('description'),
                    city_alias = entry.get('city_alias')

                )
                db.session.add(zone)

            # Update or create associated temporary zone data
            temporary_data = ZoneTemporaryData.query.filter_by(zone_id=zone_id).first()
            if temporary_data:
                temporary_data.temporary_data = entry.get('temporary_data')
                temporary_data.tp_lez_start = entry.get('tp_lez_start')
                temporary_data.tp_lez_end = entry.get('tp_lez_end')
                temporary_data.tp_minimum_diesel = entry.get('tp_minimum_diesel')
                temporary_data.tp_minimum_petrol = entry.get('tp_minimum_petrol')
            else:
                temporary_data = ZoneTemporaryData(
                    zone_id=zone_id,
                    country=entry.get('country'),
                    city=entry.get('city'),
                    temporary_data=entry.get('temporary_data'),
                    tp_lez_start=entry.get('tp_lez_start'),
                    tp_lez_end=entry.get('tp_lez_end'),
                    tp_minimum_diesel=entry.get('tp_minimum_diesel'),
                    tp_minimum_petrol=entry.get('tp_minimum_petrol')
                )
                db.session.add(temporary_data)

        # Commit the changes to the database after all entries are processed
        db.session.commit()
        return jsonify({'message': 'Zone table updated successfully.'}), 200

    except IntegrityError as e:
        db.session.rollback()
        print(e)
        return jsonify({'message': 'An error occurred with the database integrity.'}), 400

    except Exception as e:
        db.session.rollback()
        print(e)
        return jsonify({'message': 'An unexpected error occurred.'}), 500




@views.route('/info')
def general_info():
    from .models import Zone 
    countries=Zone.query.with_entities(Zone.country).distinct().all()
    countries_with_lez = [country[0].strip("()''") for country in countries]


    from .models import Zone 
    countries_with_lez =Zone.get_countries()
    cities_by_country=Zone.get_countries_and_cities()

    print("countries: ",countries_with_lez)
    return render_template("info.html", user = current_user, countries_with_lez=countries_with_lez,cities_by_country=cities_by_country)


@views.route('/info/<country>')
def country_info(country):
    country=country.upper()
    from .models import Zone 
    results = Zone.query.filter_by(country=country).with_entities(Zone.city, Zone.required_registration).order_by(Zone.city.asc()).all()
    cities = [result[0] for result in results]
    registrations = [result[1] for result in results]
    print(registrations)

    print(country)
    countries_with_lez =Zone.get_countries()
    cities_by_country=Zone.get_countries_and_cities()
    fines=Zone.get_fines(cities[0])

    print(f"cities of {country}: ", cities)


    return render_template(f"/countries_templates/info-{country.lower()}.html", user=current_user,country=country, cities=cities, registrations=registrations, countries_with_lez=countries_with_lez, cities_by_country=cities_by_country,fines=fines, zip=zip)

@views.route('/my-profile', methods=['GET','POST'])
@login_required #can only access the home page if logged in
def my_profile():
    countries_with_lez =Zone.get_countries()
    cities_by_country=Zone.get_countries_and_cities()
    return render_template("my_profile2.html", user = current_user,countries_with_lez=countries_with_lez,cities_by_country=cities_by_country)


@views.route('/new-car',methods=['POST','GET'])
@login_required
def new_car():
    from .models import Zone
    countries_with_lez =Zone.get_countries()
    cities_by_country=Zone.get_countries_and_cities()
    if request.method== 'POST':
        print("Form Data:", request.form)
        owner_id=current_user.id
        brand=request.form.get('brand')
        model=request.form.get('model')
        year=request.form.get('year')
        fuel_type=request.form.get('fuel_type')
        euro_standard=request.form.get('euro_standard')
        registration_country=request.form.get('registration_country')
        has_dpf=request.form.get('has_dpf')
        if has_dpf =='on':
            dpf=True
        else:
            dpf=False
        

        #registrations
        belgium_reg=request.form.get('Belgium_registration')
        bulgaria_reg=request.form.get('Bulgaria_registration')
        denmark_reg=request.form.get('Denmark_registration')
        france_reg=request.form.get('France_registration')
        germany_reg=request.form.get('Germany_registration')
        greece_reg=request.form.get('Greece_registration')
        netherlands_reg=request.form.get('Netherlands_registration')
        norway_reg=request.form.get('Norway_registration')
        poland_reg=request.form.get('Poland_registration')
        spain_reg=request.form.get('Spain_registration')
        uk_reg=request.form.get('United Kingdom_registration')



        if brand=='':
            flash('Please select car brand.', category='Error')
        elif model=='':
            flash("Please select car model.", category='Error')
        elif year=='':
            flash('Please select vehicle fabrication year.', category='Error')
        elif fuel_type=='':
            flash('Please select vehicle fuel type.', category='Error')
        elif euro_standard=='':
            flash('Please select vehicle Euro standard.', category='Error')

templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        crossorigin="anonymous" />
    <!-- <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script> -->

    <link rel="stylesheet" href="../static/form.css">
    <link rel="stylesheet" href="../static/navbar.css">
    <link rel="stylesheet" href="../static/base.css">
    <link rel="stylesheet" href="../static/listaa2.css">
    <link rel="stylesheet" href="../static/collapsible.css">


    <title>{% block title %}Home{% endblock %}</title>
</head>

<body>
    <nav id="navbar">
        <ul class="navbar-items">


            <!-- 
            <li class="dropdown">
                <a class="hideOnMobile" href="#" id="navbarDropdown" role="button" data-hover="dropdown"
                    aria-haspopup="true" aria-expanded="false"><img style="width: 1.9vw; margin-top: 0.9vh;"
                        alt="Drop"></i></a>
                <div class="dropdown-menu-custom" aria-labelledby="navbarDropdown">
                    {%for country in countries_with_lez%}
                    <a class="dropdown-item" href="{{ url_for('views.country_info', country=country.lower()) }}">{{
                        country }}</a>
                    {% endfor %}

                </div>
            </li> -->

            <!-- meniu stanga -->
            <li class="navbar-li">
                <div class="menu-button-container" onclick="toggleDropdown()">
                    <div class="bar1"></div>
                    <div class="bar2"></div>
                    <div class="bar3"></div>
                </div>


                <div id="description-dropdown" class="dropdown-content" style="z-index: 100;">
                    <div class="list-container2" style="position: relative; z-index: 100;">
                        <header role="banner2" style="position: relative; z-index: 100;">
                            <nav class="nav2" role="navigation2" style="position: relative; z-index: 100;">
                                <ul class="nav__list2" style="position: relative; z-index: 100;">
                                    {% for country in countries_with_lez %}
                                    <li style="position: relative; z-index: 100;">
                                        <input id="group-{{ loop.index }}2" type="checkbox" hidden />
                                        <label class="no-margin-label" for="group-{{ loop.index }}2"><span
                                                class="fa fa-angle-right2"></span><a
                                                href="{{ url_for('views.country_info', country=country) }}">{{
                                                country }}</a></label>
                                        <!-- <ul class="sub-group-list2" style="position: relative; z-index: 100;">
                                            {% for city in cities_by_country[country] %}
                                            <li><a class="exclude" href="#">{{ city }}</a></li>
                                            {% endfor %}
                                        </ul> -->
                                    </li>
                                    {% endfor %}
                                </ul>
                            </nav>
                        </header>
                    </div>
                </div>

            </li>
            <!-- --- -->

            <li class="navbar-li"><a class="goToHome" href="/">Home</a></li>
            {% if user.is_authenticated %}


            <!-- <li class="navbar-li"><a class="hideOnMobile" href="/info">INFO</a></li> -->
            <li class="navbar-li"><a class="hideOnMobile" href="/eligibility-check">Eligibility Check</a></li>
            <li class="navbar-li"><a class="hideOnMobile" href="/maps">Route planner</a></li>
            <!-- <li class="navbar-li"><a class="hideOnMobile" href="/pollution">Pollution map</a></li> -->
            {%if user.is_admin%}
            <li class="navbar-li"><a class="hideOnMobile" href="/admin_dashboard">ADMIN</a></li>
            {%endif%}
            <li class="dropdown navbar-li">
                <a class="hideOnMobile" href="#" id="navbarDropdown" role="button" data-hover="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    <img style="height: 30px; width: 30px;" src="../static/general/icons8-male-user-96.png"
                        alt=" User Icon">
                </a>
                <div class="dropdown-menu-custom" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="/my-profile">My Profile</a>
                    <a class="dropdown-item" href="/new-car">Add a new car</a>
                    <a class="dropdown-item" href="/logout">Logout</a>
                </div>
            </li>
            <li class="menu-button navbar-li" onclick="showSidebar()"><a href="#"><svg
                        xmlns="http://www.w3.org/2000/svg" height="26" viewBox="0 96 960 960" width="26">
                        <path d="M120 816v-60h720v60H120Zm0-210v-60h720v60H120Zm0-210v-60h720v60H120Z" />
                    </svg></a></li>
            {% else %}
            <!-- <li class="navbar-li"><a class="hideOnMobile" id="INFO" href="/info">INFO</a></li> -->
            <li class="navbar-li"><a class="hideOnMobile" id="login" href="/login">Login</a></li>
            <li class="navbar-li"><a class="hideOnMobile" id="signUp" href="/sign-up">Sign Up</a></li>
            <li class="menu-button navbar-li" onclick="showSidebar()"><a href="#"><svg
                        xmlns="http://www.w3.org/2000/svg" height="26" viewBox="0 96 960 960" width="26">
                        <path d="M120 816v-60h720v60H120Zm0-210v-60h720v60H120Zm0-210v-60h720v60H120Z" />
                    </svg></a></li>
            {% endif %}
        </ul>

    </nav>


    <!-- <br><br> -->
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    {% if category =='Error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    {% block content %} {% endblock %}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

    {% block javascript %}
    <script type="text/javascript">
        function deleteNote(noteId) {
            fetch("/delete-note", {
                method: "POST",
                body: JSON.stringify({ noteId: noteId }),
            }).then((_res) => {
                window.location.href = "/";
            });
        }
    </script>

    <script>
        function showSidebar() {
            const sidebar = document.querySelector('.sidebar')
            sidebar.style.display = 'flex'
        }
        function hideSidebar() {
            const sidebar = document.querySelector('.sidebar')
            sidebar.style.display = 'none'
        }

        // JavaScript to toggle dropdown visibility
        function toggleDropdown() {
            var dropdown = document.getElementById("description-dropdown");
            dropdown.classList.toggle("show");
        }



        // JavaScript to hide dropdown when clicking outside of it
        window.onclick = function (event) {
            var dropdown = document.getElementById("description-dropdown");
            var menuButtonContainer = document.querySelector('.menu-button-container');

            // Check if the clicked element is not part of the dropdown or its children
            if (!dropdown.contains(event.target) && !menuButtonContainer.contains(event.target)) {
                if (dropdown.classList.contains('show')) {
                    dropdown.classList.remove('show');
                }
            }
        }
    </script>

    <script>
        var coll = document.getElementsByClassName("collapsible");
        var i;

        for (i = 0; i < coll.length; i++) {
            // Check initial display state and set "active" class accordingly
            if (coll[i].nextElementSibling.style.display === "block") {
                coll[i].classList.add("active");
            }

            coll[i].addEventListener("click", function () {
                this.classList.toggle("active");
                var content = this.nextElementSibling;
                if (content.style.display === "block") {
                    content.style.display = "none";
                    if (content.classList.contains("active"))
                        content.classList.remove("active");

                }

                else {
                    content.style.display = "block";
                }
            });
        }
    </script>
    <script>
        document.addEventListener('DOMContentLoaded', (event) => {
            document.querySelectorAll('input').forEach(input => {
                input.addEventListener('keydown', function (event) {
                    if (event.key === 'Enter') {
                        event.preventDefault();
                    }
                });
            });
        });
    </script>
    <div class="page-content">

    </div>
    {% endblock %}


</body>

</html>

templates/info.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../static/list.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        crossorigin="anonymous" />
    <title>INO PAGE</title>
</head>

<body class="info">

    <h1>THIS PAGE CONTAINS GENERAL INFOMATION ABOUT LEZ IN EUROPE</h1>

    <div class="list-container">
        <ul list-group>
            {%for country in countries_with_lez%}
            <li class="list-group-item">
                <a href="{{ url_for('views.country_info', country=country.lower()) }}">{{ country }}</a>
            </li>
            {% endfor %}
        </ul>
    </div>



</body>

</html>

{% endblock %}

templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
%}

<body class="login">

    <div class="login-form-container">
        <form class="login-form" method="POST">
            <h3 align="center">Login</h3>
            <div class="form-group">
                <label for="email">Email Address</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Enter email" />
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" id="password" name="password"
                    placeholder="Enter password" />
            </div>
            <br />
            <button type="submit" class="btn btn-primary">Login</button>
        </form>
    </div>
</body>
{% endblock %}

templates/pollution.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block content %}

<head>
    <title>Google Maps Directions</title>
    <!-- <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDSrGZOUl7LV020hIPMv0WXyKemXGj0Vgk&libraries=places&callback=initMap"></script>
    <script src="../static/script.js"></script> -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/markerclustererplus/dist/markerclusterer.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        crossorigin="anonymous" />
    <link rel="stylesheet" href="../static/list.css">
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDSrGZOUl7LV020hIPMv0WXyKemXGj0Vgk"></script>


</head>

<body>
    <h1 align="center">Home page</h1>


    <br>


    <div id='map' style='height:380px;' />
    <!-- <script src="https://maps.googleapis.com/maps/api/js"></script> -->
    <!-- 82645b03feba4f3384606a8471f00510abc10c37 -->

</body>

<script src="../static/pollution.js"></script>
<script src="https://kit.fontawesome.com/a076d05399.js"></script>
<script src="https://cdn.jsdelivr.net/npm/markerclustererplus/dist/markerclusterer.min.js"></script>
{% endblock %}

templates/sign_up.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %} {% block
content %}

<body class="sign-up">

    <div class="login-form-container">
        <form class="login-form" method="POST">
            <h3 align="center">Sign Up</h3>
            <div class="elem-group">
                <label for="email">Your Name</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Enter email" />
            </div>
            <div class="elem-group">
                <label for="firstName">First Name</label>
                <input type="text" class="form-control" id="firstName" name="firstName"
                    placeholder="Enter first name" />
            </div>
            <div class="elem-group">
                <label for="password1">Password</label>
                <input type="password" class="form-control" id="password1" name="password1"
                    placeholder="Enter password" />
            </div>
            <div class="elem-group">
                <label for="password2">Password (Confirm)</label>
                <input type="password" class="form-control" id="password2" name="password2"
                    placeholder="Confirm password" />
            </div>
            <br />
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</body>
{% endblock %}